name: Test action
on:
  push:
jobs:
  should-trigger-deployment:
    name: Should trigger deployment
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Act
        id: deploy
        uses: './'
        with:
          token: ${{ github.token }}
          repository: ${{ github.repository }}
          ref: main
          environment: dev
          required-contexts: '[]'
          payload: '{}'
      - name: Assert
        env:
          DEPLOYMENT_ID: ${{ steps.deploy.outputs.deployment-id }}
        run: |
          echo "Deployment ID: $DEPLOYMENT_ID"
          if [[ -z "$DEPLOYMENT_ID" ]]; then
            echo "Deployment ID must be present"
            exit 1
          fi

